"""
The contract trip-wire: the production codec must reproduce every golden vector exactly.

This is the test the whole "wire-ready" idea hangs on. If the Python simulator codec and
the committed vectors (generated by the reference oracle) ever disagree, the wire format
has drifted — and this fails. The C firmware codec is held to the same vectors.

Runnable two ways:
    python3 tests/test_golden_vectors.py     # standalone, no deps
    pytest tests/test_golden_vectors.py
"""

import json
import sys
from importlib.resources import files
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from wiredaq.protocol.codec import (  # noqa: E402
    crc16_ccitt_false,
    decode,
    decode_frame,
    encode_sample_block,
)


def load_vectors():
    # Package-relative: works whether installed or run from a source checkout.
    text = files("wiredaq.protocol.golden").joinpath("vectors.json").read_text()
    return json.loads(text)["vectors"]


def test_crc_check_value():
    # The cross-language anchor: every codec must give 0x29B1 for "123456789".
    assert crc16_ccitt_false(b"123456789") == 0x29B1


def test_encode_matches_golden():
    for v in load_vectors():
        expected = bytes.fromhex(v["frame_hex"])
        got = encode_sample_block(**v["input"])
        assert got == expected, f"encode mismatch for {v['name']}"
        assert len(got) == v["frame_len"], f"frame_len mismatch for {v['name']}"


def test_decode_round_trips_golden():
    for v in load_vectors():
        frame = bytes.fromhex(v["frame_hex"])
        assert decode_frame(frame) == v["input"], f"decode mismatch for {v['name']}"


def test_decode_crc_field_matches():
    for v in load_vectors():
        frame = bytes.fromhex(v["frame_hex"])
        pkt = decode(frame)
        assert pkt.sample_count == len(v["input"]["samples"])
        # CRC stated in the vector equals the CRC over the covered bytes.
        assert f"0x{crc16_ccitt_false(frame[:-2]):04X}" == v["crc16"], v["name"]


def _run_standalone():
    tests = [
        test_crc_check_value,
        test_encode_matches_golden,
        test_decode_round_trips_golden,
        test_decode_crc_field_matches,
    ]
    for t in tests:
        t()
        print(f"  ok  {t.__name__}")
    print(f"All {len(tests)} golden-vector checks passed "
          f"({len(load_vectors())} vectors).")


if __name__ == "__main__":
    _run_standalone()
