#!/usr/bin/env python3
"""
Generate firmware/test/golden_vectors.h from protocol/golden/vectors.json.

This is the bridge that lets the C codec be held to the *same* golden vectors as the
Python codec without anything being hand-transcribed: the single source of truth stays
vectors.json, and this script projects it into a C array the test can compile against.
The header is generated (not committed by hand); the Makefile runs this before building.

    python3 firmware/test/gen_golden_header.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
VECTORS = ROOT / "src" / "wiredaq" / "protocol" / "golden" / "vectors.json"
OUT = Path(__file__).resolve().parent / "golden_vectors.h"

# Mirrors the msg_type enum in packet_schema.yaml.
MSG_TYPE_CODE = {"SAMPLE_BLOCK": 1, "HEARTBEAT": 2}


def c_array(name, ctype, values):
    if not values:
        # zero-length arrays aren't portable C; emit a 1-element dummy, length stays 0.
        return f"static const {ctype} {name}[1] = {{0}};"
    body = ", ".join(str(v) for v in values)
    return f"static const {ctype} {name}[] = {{{body}}};"


def main() -> int:
    data = json.loads(VECTORS.read_text())
    vectors = data["vectors"]

    lines = [
        "/* AUTO-GENERATED by firmware/test/gen_golden_header.py — do not edit. */",
        "/* Source of truth: protocol/golden/vectors.json */",
        "#ifndef WIREDAQ_GOLDEN_VECTORS_H",
        "#define WIREDAQ_GOLDEN_VECTORS_H",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    const char *name;",
        "    uint8_t  msg_type;",
        "    uint16_t node_id;",
        "    uint32_t seq;",
        "    uint64_t t_node_us;",
        "    uint32_t sample_rate_hz;",
        "    uint8_t  channel_count;",
        "    uint8_t  sample_count;",
        "    const int16_t *values;",
        "    size_t   n_values;",
        "    const uint8_t *frame;",
        "    size_t   frame_len;",
        "} golden_vector_t;",
        "",
    ]

    for i, v in enumerate(vectors):
        inp = v["input"]
        flat = [val for row in inp.get("samples", []) for val in row]
        frame = bytes.fromhex(v["frame_hex"])
        lines.append(c_array(f"v{i}_values", "int16_t", flat))
        lines.append(c_array(f"v{i}_frame", "uint8_t", list(frame)))
        lines.append("")

    lines.append("static const golden_vector_t GOLDEN_VECTORS[] = {")
    for i, v in enumerate(vectors):
        inp = v["input"]
        samples = inp.get("samples", [])
        flat_len = sum(len(row) for row in samples)
        t = inp["t_node_us"]
        lines.append(
            "    {{ \"{name}\", {mt}u, {nid}u, {seq}u, {t}ull, {rate}u, {ch}u, {sc}u, "
            "v{i}_values, {nv}u, v{i}_frame, {fl}u }},".format(
                name=v["name"], mt=MSG_TYPE_CODE[v.get("msg_type", "SAMPLE_BLOCK")],
                nid=inp["node_id"], seq=inp["seq"], t=t,
                rate=inp["sample_rate_hz"], ch=inp.get("channel_count", 0),
                sc=len(samples), i=i, nv=flat_len, fl=len(frame_for(v)),
            )
        )
    lines.append("};")
    lines.append("")
    lines.append(f"#define GOLDEN_VECTOR_COUNT {len(vectors)}u")
    lines.append("")
    lines.append("#endif /* WIREDAQ_GOLDEN_VECTORS_H */")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(vectors)} vectors to {OUT.relative_to(ROOT)}")
    return 0


def frame_for(v):
    return bytes.fromhex(v["frame_hex"])


if __name__ == "__main__":
    raise SystemExit(main())
