/*
 * The C-side contract trip-wire: the firmware codec must reproduce every golden
 * vector exactly, and decode each one back to the same fields.
 *
 * This is the cross-language byte-compatibility proof. If the C codec and the
 * committed vectors (generated by the Python oracle) ever disagree, the firmware
 * has drifted from the wire format — and this fails. Same vectors, same bytes as
 * tests/test_golden_vectors.py on the Python side.
 *
 * golden_vectors.h is generated from src/wiredaq/protocol/golden/vectors.json by
 * gen_golden_header.py (the Makefile runs it first).
 */
#include <stdio.h>
#include <string.h>

#include "wiredaq_codec.h"
#include "golden_vectors.h"

static int g_failures = 0;

static void hexdump(const char *label, const uint8_t *b, size_t n)
{
    printf("    %s: ", label);
    for (size_t i = 0; i < n; ++i) printf("%02x", b[i]);
    printf("\n");
}

static int check_crc_self_test(void)
{
    uint16_t crc = wd_crc16_ccitt_false((const uint8_t *)"123456789", 9);
    if (crc != 0x29B1u) {
        printf("  FAIL crc self-test: expected 0x29B1, got 0x%04X\n", crc);
        return 1;
    }
    printf("  ok   crc self-test (0x29B1)\n");
    return 0;
}

static void check_vector(const golden_vector_t *v)
{
    /* --- encode: fields -> bytes, must equal the golden frame exactly --- */
    wd_packet_t pkt;
    memset(&pkt, 0, sizeof pkt);
    pkt.node_id        = v->node_id;
    pkt.seq            = v->seq;
    pkt.t_node_us      = v->t_node_us;
    pkt.sample_rate_hz = v->sample_rate_hz;
    pkt.channel_count  = v->channel_count;
    pkt.sample_count   = v->sample_count;
    for (size_t i = 0; i < v->n_values; ++i) pkt.values[i] = v->values[i];

    uint8_t out[WD_MAX_PACKET_BYTES];
    size_t out_len = 0;
    wd_status_t st = (v->msg_type == WD_MSG_HEARTBEAT)
        ? wd_encode_heartbeat(v->node_id, v->seq, v->t_node_us, v->sample_rate_hz,
                              out, sizeof out, &out_len)
        : wd_encode_sample_block(&pkt, out, sizeof out, &out_len);

    int ok = 1;
    if (st != WD_OK) {
        printf("  FAIL %-24s encode returned %d\n", v->name, st);
        ok = 0;
    } else if (out_len != v->frame_len || memcmp(out, v->frame, v->frame_len) != 0) {
        printf("  FAIL %-24s encode bytes differ (got %zu, want %zu)\n",
               v->name, out_len, v->frame_len);
        hexdump("got ", out, out_len);
        hexdump("want", v->frame, v->frame_len);
        ok = 0;
    }

    /* --- decode: golden bytes -> fields, must match the input --- */
    wd_packet_t dec;
    memset(&dec, 0, sizeof dec);
    st = wd_decode_frame(v->frame, v->frame_len, &dec);
    if (st != WD_OK) {
        printf("  FAIL %-24s decode returned %d\n", v->name, st);
        ok = 0;
    } else {
        int fields_ok = dec.msg_type == v->msg_type
            && dec.node_id == v->node_id
            && dec.seq == v->seq
            && dec.t_node_us == v->t_node_us
            && dec.sample_rate_hz == v->sample_rate_hz
            && dec.channel_count == v->channel_count
            && dec.sample_count == v->sample_count;
        for (size_t i = 0; i < v->n_values; ++i)
            if (dec.values[i] != v->values[i]) fields_ok = 0;
        if (!fields_ok) {
            printf("  FAIL %-24s decode fields differ\n", v->name);
            ok = 0;
        }
    }

    if (ok) printf("  ok   %-24s len=%zu\n", v->name, v->frame_len);
    else    g_failures++;
}

static int check_crc_rejects_corruption(void)
{
    /* Flip one payload bit in the first vector that has a payload; decode must
     * reject it as WD_ERR_CRC, never silently accept it. */
    for (size_t i = 0; i < GOLDEN_VECTOR_COUNT; ++i) {
        const golden_vector_t *v = &GOLDEN_VECTORS[i];
        if (v->frame_len <= WD_HEADER_SIZE + WD_CRC_SIZE) continue; /* no payload */
        uint8_t buf[WD_MAX_PACKET_BYTES];
        memcpy(buf, v->frame, v->frame_len);
        buf[WD_HEADER_SIZE] ^= 0x01;  /* corrupt first payload byte */
        wd_packet_t dec;
        wd_status_t st = wd_decode_frame(buf, v->frame_len, &dec);
        if (st != WD_ERR_CRC) {
            printf("  FAIL corruption check on %s: expected WD_ERR_CRC, got %d\n",
                   v->name, st);
            return 1;
        }
        printf("  ok   crc rejects corruption (via %s)\n", v->name);
        return 0;
    }
    return 0;
}

int main(void)
{
    printf("WireDAQ firmware codec — golden-vector conformance\n");
    int rc = 0;
    rc |= check_crc_self_test();
    for (size_t i = 0; i < GOLDEN_VECTOR_COUNT; ++i) check_vector(&GOLDEN_VECTORS[i]);
    rc |= check_crc_rejects_corruption();

    if (g_failures || rc) {
        printf("FAILED: %d vector failure(s)%s\n", g_failures,
               rc ? " + a self-test failure" : "");
        return 1;
    }
    printf("All %u golden vectors reproduced byte-for-byte. PASS\n",
           GOLDEN_VECTOR_COUNT);
    return 0;
}
